# === DATABASE CONNECTION ===
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_budget
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# === HIBERNATE / JPA ===
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# === SQL LOGGING (DEV) ===
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# === CONNECTION POOL (Hikari) ===
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# === TIMEZONE ===
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# = SERVER
server.port=8080

# === KAFKA CONFIG ===
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=smart-budget-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.StringDeserializer